---
base_packages:
  - cockpit
  - podman
  - container-selinux
  - firewalld
  - nano
  - bash-completion
  #- cockpit-podman
  #- container-tools

rhel7_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms

rhel8_repos:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - codeready-builder-for-rhel-8-x86_64-rpms

rhel9_repos:
  - rhel-9-for-x86_64-baseos-rpms
  - rhel-9-for-x86_64-appstream-rpms
  - codeready-builder-for-rhel-9-x86_64-rpms

setup_cockpit: true

container_http_port: 8080

container_image: registry.access.redhat.com/ubi8/httpd-24:1-294
container_www_root: /opt/www-root
container_name: httpd
#RHEL-8.10.0-20231111.2