---
- name: Enable the repos for RHEL 7
  when: ansible_distribution_major_version == "7"
  community.general.rhsm_repository:
    name: "{{ rhel7_repos }}"
    state: enabled

- name: Enable the repos for RHEL 8
  when: ansible_distribution_major_version == "8"
  community.general.rhsm_repository:
    name: "{{ rhel8_repos }}"
    state: enabled

- name: Enable the repos for RHEL 9
  when: ansible_distribution_major_version == "9"
  community.general.rhsm_repository:
    name: "{{ rhel9_repos }}"
    state: enabled
